export const SITE_NAME = 'Shayders';
export const SITE_URL = 'https://shayders.ayfri.com';
export const SITE_DESCRIPTION = 'Shayders is an online GLSL shader editor to write WebGL fragment shaders with a live preview, multipass buffers and image, video or webcam channels, then share them with the community.';
export const SITE_REPOSITORY_URL = 'https://github.com/Ayfri/shayders';
export const SITE_TWITTER_HANDLE = '@Ayfri_';
/** Generated by `bun run og-image`, 1200x630. */
export const SITE_OG_IMAGE = { alt: 'Shayders, write, preview and share GLSL shaders right in your browser', height: 630, path: '/og-image.png', width: 1200 } as const;
/** Same identity as the JSON-LD of ayfri.com so search engines merge both sites under one creator. */
export const SITE_AUTHOR = {
	'@id': 'https://ayfri.com/#person',
	'@type': 'Person',
	alternateName: 'Ayfri',
	image: 'https://ayfri.com/images/avatar.png',
	name: 'Pierre Roy',
	sameAs: [
		'https://github.com/Ayfri',
		'https://www.linkedin.com/in/pierre-roy-ayfri/',
		'https://www.twitch.tv/ayfri_',
		'https://twitter.com/Ayfri_',
	],
	url: 'https://ayfri.com',
} as const;
export const SITE_SEARCH_PATH = '/search';
export const SITE_SEARCH_URL_TEMPLATE = `${SITE_URL}${SITE_SEARCH_PATH}?q={search_term_string}`;

export function buildSiteUrl(pathOrUrl: string): string {
	if (/^https?:\/\//i.test(pathOrUrl)) {
		return pathOrUrl;
	}

	const path = pathOrUrl.startsWith('/') ? pathOrUrl : `/${pathOrUrl}`;
	return new URL(path, SITE_URL).toString();
}

export function getUserProfilePath(userId: string): string {
	return `/users/${userId}`;
}

export function getShaderPath(shaderId: string): string {
	return `/shader/${shaderId}`;
}

/**
 * PocketBase dates use a space separator that schema.org and Open Graph parsers reject.
 * @example toIsoDate('2026-03-26 02:18:29.920Z') === '2026-03-26T02:18:29.920Z'
 */
export function toIsoDate(pocketBaseDate: string): string {
	return new Date(pocketBaseDate.replace(' ', 'T')).toISOString();
}

export type JsonValue = string | number | boolean | null | readonly JsonValue[] | { readonly [key: string]: JsonValue | undefined };
export type JsonLdNode = { readonly [key: string]: JsonValue | undefined };

/** Serializes schema.org data for a `<script type="application/ld+json">`, `<` is escaped so user text can never close the script tag. */
export function serializeJsonLd(data: JsonLdNode | readonly JsonLdNode[]): string {
	return JSON.stringify(Array.isArray(data) ? { '@context': 'https://schema.org', '@graph': data } : { '@context': 'https://schema.org', ...data })
		.replaceAll('<', '\\u003c');
}

/**
 * Cuts text on a word boundary for meta descriptions.
 * @example truncateText('A very long description', 10) === 'A very…'
 */
export function truncateText(text: string, maxLength = 155): string {
	const clean = text.replace(/\s+/g, ' ').trim();
	if (clean.length <= maxLength) return clean;
	const cut = clean.slice(0, maxLength - 1);
	const lastSpace = cut.lastIndexOf(' ');
	return `${(lastSpace > maxLength / 2 ? cut.slice(0, lastSpace) : cut).replace(/[\s,.;:!?-]+$/, '')}…`;
}
